import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * The part categories and their pages are generated from the contents of
 * `docs/parts`, which mirrors `src/data/book.ts`. Labels and ordering come
 * from the `_category_.json` of each part and from the frontmatter of each
 * page, so this file does not need to change when a page is added.
 */
const sidebars: SidebarsConfig = {
  solutionsSidebar: ['intro', { type: 'autogenerated', dirName: 'parts' }]
}

export default sidebars
